### ISSUE TITLE
Fail when using Jest@26

### ISSUE THREAD

**Issue by brisberg** [eduter/screeps-jest#5]
Fails when using the latest version of Jest (26.1.0).

Jest now access a few internal calls on mocked functions with trigger the "unmocked properties" safe guard.

```
Unexpected access to unmocked property "Memory._isMockFunction".
    Did you forget to mock it?
    If you intended for it to be undefined, you can explicitly set it to undefined (recommended) or set "allowUndefinedAccess" argument to true.

      at Object.get (node_modules/screeps-jest/src/mocking.js:66:23)
          at Array.forEach (<anonymous>)
```

```
TypeError: globalMock.mockClear is not a function

      at Object.keys.forEach.key (node_modules/jest-runtime/build/index.js:939:24)
          at Array.forEach (<anonymous>)
```

----

Interesting issue with reproducing this with your test cases. Pulling the repo and upgrading to Jest 26 still causes all the tests to pass. However, if you `SKIP` the test about `mockGlobal` where `allowUndefined` is true, the other tests fail with the above errors.

I am guessing that something is not being cleaned up correctly between cases, as those tests should be independent.

**Comment by eduter** [comment]
Thanks for finding and fixing the problem!

**Comment by brisberg** [comment]
Do you mind doing another release? (or at least just a tag).

I'd feel better updating my dependency to a locked version than to `master` itself where it might pull in future commits without warning.
